### PR TITLE
fix crack on shutdown

### PR DESCRIPTION
**Pull request by gastonfeng**

### CODE REVIEW

**Comment by MrYsLab** [comment]
Thanks for the pull request, but I am not sure what problem this fixes. Could you please provide a description of the problem? Thanks.

**Comment by MrYsLab** [comment]
I still don't understand what the problem is that this pull request solves. Could you please provide an example that demonstrates the issue?

**Comment by MrYsLab** [comment]
I am closing this pull request since I do not know what the actual problem is or how to recreate it. If you wish to proceed with this PR, please provide a detailed description of the problem and a sample program to recreate it. 
Thanks.

**Comment by gastonfeng** [comment]
send_reset after shutdown , so crack.
i moved shutdown to after send_reset.

**Comment by martynwheeler** [comment]
What do you mean by crack?  You need to provide more details of the problem and what your fix is doing.  Please explain the changes you are proposing to the code and how they address the problem that you have encountered.

Thanks

**Comment by MrYsLab** [comment]
@gastonfeng Please provide a brief python script that demonstrates the issue you are seeing. I need to be able to understand the problem before considering any changes to the code. Thanks.

**Pull request closed without merging**
